-- ============================================================
--  Ben Maker Studio - Database schema
--  Alternative to install.php: import this in phpMyAdmin.
--  (install.php is easier because it also creates the admin.)
-- ============================================================

CREATE DATABASE IF NOT EXISTS `ben_maker` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ben_maker`;

CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL DEFAULT 0,
    category VARCHAR(80) DEFAULT 'General',
    image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(60),
    product_id INT NULL,
    subject VARCHAR(200),
    body TEXT NOT NULL,
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- NOTE: password_hash values must be generated by PHP.
-- If you import this file manually, create the admin by visiting install.php,
-- or run this after generating a hash with password_hash('yourpass', PASSWORD_DEFAULT):
-- INSERT INTO admins (username, password_hash) VALUES ('admin', '<PASTE_HASH_HERE>');
